### ISSUE TITLE
Issue with outputfile parameter

### ISSUE THREAD

**Issue by tailon2k** [HerrEurobeat/output-logger#1]
When the `outputfile` parameter is set to an empty string, the file is still created. The expected behavior is that if the `outputfile` is an empty string, no file should be created. Instead, it behaves as if the parameter was not provided, triggering the default behavior to create the file. (Or at least that's what I think)

Here is the code I have, and it still creates the file:

```javascript
logger.options({
    msgstructure: `[${logger.Const.ANIMATION}] [${logger.Const.DATE} | ${logger.Const.TYPE}] ${logger.Const.MESSAGE}`,
    paramstructure: [logger.Const.TYPE, logger.Const.MESSAGE, "nodate", "remove", logger.Const.ANIMATION],
    outputfile: "",
    exitmessage: "",
    printdebug: false
});

**Comment by 3urobeat** [comment]
Oops, yeah, you are totally correct. Thanks for noticing and reporting.  
Version 2.3.8, which fixes this issue, should be available on npm in a moment.
